### ISSUE TITLE
Process `pipeline:preArticQC (1)` terminated with an error exit status (127)

### ISSUE THREAD

**Issue by xxu1022** [epi2me-labs/wf-artic#32] opened 2022-01-15 08:54 UTC
Hi,
Is any one can help me on the error (127)? Detail information is as follows. Thanks!

$ /home/grid/program/nextflow run epi2me-labs/wf-artic --scheme_name SARS-CoV-2 --scheme_version V1200 --min_len 200 --max_len 1100 --our_dir midnight --fastq sars_cov_2_reads/ -resume
N E X T F L O W  ~  version 21.10.6
Launching `epi2me-labs/wf-artic` [drunk_mercator] - revision: 8d13aab29f [master]

WARN: Found unexpected parameters:
* --our_dir: midnight
- Ignore this warning: params.schema_ignore_params = "our_dir"

Core Nextflow options
  revision       : master
  runName        : drunk_mercator
  containerEngine: docker
  launchDir      : /home/grid/data/wf_artic
  workDir        : /home/grid/data/wf_artic/work
  projectDir     : /home/grid/.nextflow/assets/epi2me-labs/wf-artic
  userName       : grid
  profile        : standard
  configFiles    : /home/grid/.nextflow/assets/epi2me-labs/wf-artic/nextflow.config

Basic Input/Output Options
  fastq          : sars_cov_2_reads/

Primer Scheme Selection
  scheme_version : V1200

Advanced options
  min_len        : 200
  max_len        : 1100

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use wf-artic for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

Checking input directory structure.
 - Found barcode directories
executor >  local (3)
executor >  local (3)
[ae/d15473] process > pipeline:getVersions    [100%] 1 of 1, failed: 1 ✘
[be/7ad0fc] process > pipeline:getParams      [100%] 1 of 1, cached: 1 ✔
[-        ] process > pipeline:copySchemeDir  -
[24/9dd3be] process > pipeline:preArticQC (1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:runArtic       -
[-        ] process > pipeline:allConsensus   -
[-        ] process > pipeline:allVariants    -
[-        ] process > pipeline:nextclade      -
[-        ] process > pipeline:pangolin       -
[-        ] process > pipeline:telemetry      -
[-        ] process > pipeline:report         -
[-        ] process > output                  -
Error executing process > 'pipeline:preArticQC (1)'

Caused by:
  Process `pipeline:preArticQC (1)` terminated with an error exit status (127)

Command executed:

  fastcat -s barcode01 -r barcode01.stats -x barcode01 > /dev/null

Command exit status:
  127

Command output:
  (empty)

Command error:
  /bin/bash: .command.run: No such file or directory

Work dir:
  /home/grid/data/wf_artic/work/24/9dd3be42bf36ee9ba8124473a00c7e

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by bede** [comment] 2022-01-15 12:17
I think the the problem is that ‘—our_dir’ should be ‘—out_dir’

**Comment by xxu1022** [comment] 2022-01-15 12:35
Thanks for the reminder of the mistake. Now I change to '--out_dir' but the error still appear and the error still is command error '/bin/bash: .command.run: No such file or directory'.

Checking input directory structure.
WARN: Killing pending tasks (2)
executor >  local (4)
[05/43b6ac] process > pipeline:getVersions    [  0%] 0 of 1
executor >  local (4)
[-        ] process > pipeline:getVersions    -
[b4/50d933] process > pipeline:getParams      [100%] 1 of 1 ✔
[5d/bbe943] process > pipeline:copySchemeDir  [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:preArticQC (1) -
[-        ] process > pipeline:runArtic       -
[-        ] process > pipeline:allConsensus   -
[-        ] process > pipeline:allVariants    [  0%] 0 of 1
[-        ] process > pipeline:nextclade      -
[-        ] process > pipeline:pangolin       -
[-        ] process > pipeline:telemetry      [  0%] 0 of 1
[-        ] process > pipeline:report         -
[-        ] process > output                  -
Error executing process > 'pipeline:copySchemeDir'

**Caused by:
  Process `pipeline:copySchemeDir` terminated with an error exit status (127)**

Command executed:

  cp -RL primer_schemes scheme_dir

Command exit status:
  127

Command output:
  (empty)

**Command error:
  /bin/bash: .command.run: No such file or directory**

Work dir:
  /home/grid/data/wf_artic/work/5d/bbe9434be6ed8f3ea58e054eaa8726

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by bede** [comment] 2022-01-15 13:51
I'd try removing`--scheme_name SARS-CoV-2`

`--scheme_version V1200` should be sufficient

**Comment by xxu1022** [comment] 2022-01-15 16:03
Thanks for your suggestion on this. I have tried removing '--scheme_name SARS-CoV-2'. But it still not work and still is the same error info 'terminated with an error exit status (127)' and '/bin/bash: .command.run: No such file or directory'. 
Any further suggestion on this? Thanks!

**Comment by mattdmem** [comment] 2022-01-16 12:28
Can you please provide a little more information on how you're running this? What's the operating system? Or are you running on a GridION?

**Comment by xxu1022** [comment] 2022-01-16 14:01
Hi, Thanks for your comments on this. 
For your information, I am trying to run 'epi2me-labs/wf-artic' on subsystem (Ubuntu 20.04 focal) of Win10. I have installed docker on Win10 and on Ubuntu subsystem as well. Miniconda and nextflow have been installed on Ubuntu subsystem as well. The command 'nextflow run epi2me-labs/wf-artic --help' works well for me. 
Feel free to let me know if any more information is needed.
Best,

**Comment by mattdmem** [comment] 2022-01-16 14:02
https://labs.epi2me.io/nextflow-on-windows/ <- check this out and see if it's of any use.

**Comment by mattdmem** [comment] 2022-01-24 16:00
Hi @xxu1022 - any updates - have you got the workflow running now?

**Comment by xxu1022** [comment] 2022-01-28 11:25
Hi @mattdmem Thanks for your considering this. I am still struggling with the same issue.
 I assume that it is the docker issue in Ubuntu subsystem, since I use the subsystem Ubuntu focal on Win10.
1) The docker is installed on both in Ubuntu subsystem and win10 system as well. 
2) I have successfully run epi2me-labs in Win10 and use the docker app in win10 system as well.

 Is uninstall-install the docker in ubuntu subsystem works for this issue? 
And how to uninstall docker in subsystem ubuntu focal?

Thanks

**Comment by sarahjeeeze** [comment] 2022-01-28 15:55
Hi @xxu1022, I would suggest trying `nextflow pull epi2me-labs/wf-artic` and running the cmd again. Also whilst the workflow is running could you check the container is running with `docker ps -a` you would need to do that in another terminal or by adding `-bg` to your initial nextflow command to allow you to keep using the current terminal.

**Comment by mattdmem** [comment] 2022-02-08 09:23
@xxu1022 did you manage to get it working? If so I'll close this issue!

**Comment by xxu1022** [comment] 2022-02-11 03:05
Hi sarahjeeeze and mattdmem, Thanks for your comments and sorry for the late reply. I have tried ' nextflow pull epi2me-labs/wf-artic' first. The output is 'Checking epi2me-labs/wf-artic':
 Fast-forward - revision: eeb43e96f7 [master]'.
While when I tried the 'nextflow run epi2me-labs/wf-artic --fastq sars-cov-2' with the other parameter as default, it stopped with the following error information very quickly. The output of  'docker ps -a' in another terminal is 'Cannot connect to the Docker daemon at unix://var/run/docker.sock. Is the docker daemon running?'.

Error information:
Error executing process > 'pipeline:getParams'

Caused by:
  Process `pipeline:getParams` terminated with an error exit status (125)

Command executed:

  # Output nextflow params object to JSON
      echo '{
      "help": false,
      "out_dir": "output",
      "fastq": "sars_cov_2_reads/",
      "sanitize_fastq": false,
      "sample": null,
      "sample_sheet": null,
      "normalise": 200,
      "report_depth": 100,
      "medaka_model": "r941_prom_variant_g360",
      "scheme_name": "SARS-CoV-2",
      "scheme_version": "V3",
      "genotype_variants": null,
      "report_clade": true,
      "report_lineage": true,
      "report_coverage": true,
      "report_variant_summary": true,
executor >  local (5)
[-        ] process > pipeline:getVersions    -
[fc/ddd833] process > pipeline:getParams      [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:copySchemeDir  -
[80/ae3fb8] process > pipeline:preArticQC (1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:runArtic       -
[-        ] process > pipeline:allConsensus   -
[-        ] process > pipeline:allVariants    -
[92/37dc6f] process > pipeline:prep_nextclade [100%] 1 of 1, failed: 1 ✘
[-        ] process > pipeline:nextclade      -
[-        ] process > pipeline:pangolin       -
[-        ] process > pipeline:telemetry      -
[-        ] process > pipeline:report         -
[-        ] process > output                  -
Error executing process > 'pipeline:getParams'

Caused by:
  Process `pipeline:getParams` terminated with an error exit status (125)

Command executed:

  # Output nextflow params object to JSON
      echo '{
      "help": false,
      "out_dir": "output",
      "fastq": "sars_cov_2_reads/",
      "sanitize_fastq": false,
      "sample": null,
      "sample_sheet": null,
      "normalise": 200,
      "report_depth": 100,
      "medaka_model": "r941_prom_variant_g360",
      "scheme_name": "SARS-CoV-2",
      "scheme_version": "V3",
      "genotype_variants": null,
      "report_clade": true,
      "report_lineage": true,
      "report_coverage": true,
      "report_variant_summary": true,
      "report_detailed": false,
      "wfversion": "v0.3.11",
      "pangolin_version": "3.1.20",
      "nextclade_version": "1.10.2",
      "nextclade_data_tag": null,
      "update_data": false,
      "aws_image_prefix": null,
      "aws_queue": null,
      "lab_id": null,
      "testkit": null,
      "report_name": "report",
      "monochrome_logs": false,
      "validate_params": true,
      "show_hidden_params": false,
      "schema_ignore_params": "show_hidden_params,validate_params,monochrome_logs,aws_queue,aws_image_prefix,pangolin_version,nextclade_version,wfversion",
      "_min_len": 400,
      "_max_len": 700,
      "_max_softclip_length": 0,
      "full_scheme_name": "SARS-CoV-2/V3"
  }' > params.json

Command exit status:
  125

Command output:
  (empty)

Command error:
  docker: Cannot connect to the Docker daemon at unix://var/run/docker.sock. Is the docker daemon running?.
  See 'docker run --help'.

Work dir:
  /home/grid/data/wf_artic/work/fc/ddd833be3f7203c493532bb10f64e5

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line.

**Comment by mattdmem** [comment] 2023-08-24 18:43
@xxu1022 this issue is very old now... if you are still having problems then please post a new issue with the details!

Thanks

Matt

**Closed by mattdmem** 2023-08-24 18:43 UTC
